// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVgUX1XTAWP16Pdy47AMPd7jfUmoM-xqU',
    appId: '1:93011650698:web:cc3f5948a1257ea230a573',
    messagingSenderId: '93011650698',
    projectId: 'e-commerce-app-28531',
    authDomain: 'e-commerce-app-28531.firebaseapp.com',
    storageBucket: 'e-commerce-app-28531.appspot.com',
    measurementId: 'G-9PY7Z33V88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5zZkUGvasUYOn4KLSJpnEHdnCJAT8yFU',
    appId: '1:93011650698:android:6be769a00e52c0d530a573',
    messagingSenderId: '93011650698',
    projectId: 'e-commerce-app-28531',
    storageBucket: 'e-commerce-app-28531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG42-bitU9StOUG6TwtlW-hczYfK_HTws',
    appId: '1:93011650698:ios:a3923406c4bb166f30a573',
    messagingSenderId: '93011650698',
    projectId: 'e-commerce-app-28531',
    storageBucket: 'e-commerce-app-28531.appspot.com',
    androidClientId: '93011650698-mciieoatlmeq3m58s230d344b4h4bu2a.apps.googleusercontent.com',
    iosClientId: '93011650698-8me0eh3g1vbm60olscfci8ed78uahnli.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG42-bitU9StOUG6TwtlW-hczYfK_HTws',
    appId: '1:93011650698:ios:0645e123e7f302d230a573',
    messagingSenderId: '93011650698',
    projectId: 'e-commerce-app-28531',
    storageBucket: 'e-commerce-app-28531.appspot.com',
    androidClientId: '93011650698-mciieoatlmeq3m58s230d344b4h4bu2a.apps.googleusercontent.com',
    iosClientId: '93011650698-sjqkhsf3jrvguhnn0ha75ajik8u7toc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppV2.RunnerTests',
  );
}
